version: '3'
services:
    db:
        image: mysql:latest
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - mynet
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: root-password
            MYSQL_DATABASE: opencart
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin

    opencart:
        image: apache-php:opencart
        ports: 
            - "4000:80"
        networks:
            - mynet
        links:
            - db
        
volumes:
    db_data:

networks:
    mynet:
